pbta-aw:
  title: Apocalypse World
  text: |
    A post-apocalyptic roleplaying game by [Vincent
    Baker](https://lumpley.games/) which has inspired a whole class of
    games collectively called [glo:pbta].

coc:
  title: Call of Cthulhu
  abbr: CoC
  use_abbr_for_glo_link: false
  text: |
    A horror investigation roleplaying game based on the fiction of
    [H. P. Lovecraft](https://en.wikipedia.org/wiki/H._P._Lovecraft).
    First published in 1981 by [Chaosium](https://www.chaosium.com/),
    and now in its seventh edition.

    Unlike [glo:dnd], Call of Cthulhu has no classes or levels and has
    an extensive skill list.  The default setting is the 1920s, often
    in the USA, but supplements exist for different periods and
    locations.

dice-notation:
  title: Dice Notation
  text: |
    Dice rolls are expressed in the form `NdS`, where `N` is the
    number of dice to roll and `S` is the size of die.  Modifiers can
    be given with `+M` or `-M`.  Usually the values of the dice are
    summed to get the result.

    For example, `3d10+7` means "roll three 10-sided dice, sum them,
    and add 7 to the result".

    There are two common exceptions:

      - `d100`, or "percentile dice".  Very few people own an actual
        100-sided die, so usually this is done by rolling `2d10` and
        designating one die the "tens" place and the other the "ones"
        place.  Or equivalently, rolling `10Ã—d10 + d10`.

        For example, rolling a 3 and a 7 is read as 37.

        A roll of 0 on both dice is read as 100.

      - `d66`, `d666`, and so on.  Similarly to percentile dice, this
        usually means to roll multiple dice and read them as digits of
        a larger number.

        For example, rolling a 1, a 3, and a 6 is read as 136.

        Since a `d6` is numbered from 1 to 6, the results of a `d66`
        (for example) do not cover all values from 1 to 66.

dnd:
  title: Dungeons & Dragons
  abbr: "D&D"
  text: |
    The most popular roleplaying game, created in the 1970s by Gary
    Gygax and Dave Arneson.

godbound:
  title: Godbound
  text: |
    An [glo:osr] game by [Sine Nomine Publishing](https://sine-nomine-publishing.myshopify.com/pages/about-us)
    about being divine heroes in an apocalyptic fantasy world.

gm:
  title: Game Master, Dungeon Master, Keeper, Referee, etc
  abbr: GM
  text: |
    The player at the table who plays the part of "the world", rather
    than controlling a specific [glo:pc].  The GM will describe the
    events taking place, decide what happens when outcomes are
    uncertain and control [glos:npc].  Traditionally the GM will also
    handle out-of-game concerns like scheduling.

    The GM is not *opposed* to the PCs; they're not trying to win or
    to score points against the other players.  Even though they have
    a different role, they are still a player.

npc:
  title: Non-Player Character
  abbr: NPC
  text: |
    A character in the game world which is controlled by the [glo:gm].
    These will be your shopkeepers, guards, aristocrats, monsters, and
    so on.

osr:
  title: Old School Renaissance
  abbr: OSR
  text: |
    A movement to go back to the origins of the hobby which, in
    practice, usually means games based on early editions of
    [glo:dnd].

    Described in the [Principia Apocrypha](https://lithyscaphe.blogspot.com/p/principia-apocrypha.html):

    > The more of the following a campaign has, the more old school it
    > is: high lethality, an open world, a lack of pre-written plot,
    > an emphasis on creative problem solving, an exploration-centered
    > reward system (usually XP for treasure), a disregard for
    > "encounter balance", and the use of random tables to generate
    > world elements that surprise both players and referees.  Also, a
    > strong do-it-yourself attitude and a willingness to share your
    > work and use the creativity of others in your game.

pbta:
  title: Powered by the Apocalypse
  abbr: PbtA
  text: |
    Games inspired by [glo:pbta-aw].

    There is no generic "[glo:pbta] system", rather these are games
    built on the same principles.  As Vincent Baker, the creator of
    [glo:pbta-aw], has said:

    > Is Apocalypse World an inspiration for your game? Enough so that
    > you want to call your game [glo:pbta]? Did you follow Meg's and
    > my policy wrt publishing it? Then cool, your game is Powered by
    > the Apocalypse. Get with us if you want to use the logo.

    [glo:pbta] games tend to focus on emulating a specific genre, have
    player-facing rolls, and use playbooks instead of classes.

pc:
  title: Player Character
  abbr: PC
  text: |
    A character in the game world which is controlled by one of the
    players at the table.  Usually each player has exactly one PC,
    which they have exclusive control over, but that is not
    necessarily the case.

traveller:
  title: Traveller
  text: |
    A far-future sci-fi roleplaying game, first created in 1977
    by [Marc Miller](https://en.wikipedia.org/wiki/Marc_Miller_(game_designer)),
    with two editions currently in print: [Mongoose Traveller 2e](https://www.mongoosepublishing.com/)
    and [Traveller5](https://traveller5.net/).

    Traveller is notable for being a skill-based game, with very slow
    character advancement (getting better gear is more common than
    improving your stats), and using a lifepath character creation
    system.

    Legend has it that [Firefly was based on a Traveller campaign](https://scifi.stackexchange.com/a/13703).

troika:
  title: Troika!
  text: |
    A science-fantasy roleplaying game, based on the old [Fighting
    Fantasy](https://en.wikipedia.org/wiki/Fighting_Fantasy) system,
    written by [Daniel Sell](https://twitter.com/Ignus1).

    Despite not being based on an old edition of [glo:dnd], generally
    considered part of the [glo:osr].  The game has backgrounds,
    rather than classes, and uses a [glo:dice-notation "`2d6`"]
    roll-under system as its core mechanic.

    The default setting is in the spirit of the *Dying Earth* and
    *Book of the New Sun*.

west-marches:
  title: West Marches
  text: |
    A style of play popularised by [a series of blog posts by Ben Robbins](http://arsludi.lamemage.com/index.php/78/grand-experiments-west-marches/)
    which set out to be the opposite of a standard campaign:

    - There isn't a regular session time: the players handle the
      scheduling.

    - There isn't a regular party: there's a pool of players who party
      up based on their goals.

    - There isn't a regular plot: the players decide where to go and
      what to do.

    The usual setting is a frontier, where the [glos:pc] are
    explorers, venturing out into the wilderness for gold and glory.
    They have a safe home base, which every adventure starts and ends
    in; a partial map (left by previous adventurers); and rumours of
    what's out there.  Everything else is up to the players.
